config/routes.rb
Rails.application.routes.draw do
  root 'workshops#index'
  get 'workshops/:id' => 'workshops#show', as: 'workshop'
  post 'user_workshops/:workshop_id' => 'user_workshops#create', as: 'create_user_workshop'
  post 'workshops/:id/post' => 'posts#create', as: 'workshop_post'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user_workshop
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_workshops
end

app/models/user_workshop.rb
class UserWorkshop < ApplicationRecord
  belongs_to :user
  belongs_to :workshop
  has_many :posts
end

app/models/workshop.rb
class Workshop < ApplicationRecord
  has_many :user_workshops
  has_many :posts, through: :user_workshops

  def joined?(user)
    UserWorkshop.where(user_id: user.id, workshop_id: self.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.new(post_params)
    @post.user_workshop_id = params[:id]
    if @post.save
      redirect_to workshop_path(params[:id])
    else
      render 'workshops/show'
    end
  end

  private
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/user_workshops_controller.rb
class UserWorkshopsController < ApplicationController
  def create
    @user_workshop = UserWorkshop.create(user_id: current_user.id, workshop_id: params[:workshop_id])
    redirect_to workshop_path(params[:workshop_id])
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  def index
    @workshops = Workshop.all
  end

  def show
    @workshop = Workshop.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    User.find_by(id: 7)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_workshops_helper.rb
module UserWorkshopsHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/workshops/index.html.erb
<h1>Workshops#index</h1>
<p>Find me in app/views/workshops/index.html.erb</p>
<% @workshops.each do |workshop| %>
  <p>
    <%= link_to workshop.name, workshop_path(workshop.id) %>
  </p>
<% end %>

app/views/workshops/show.html.erb
<% if @workshop != nil %>
  <%= @workshop.name %><br>
  <% if @workshop.joined?(current_user) %>
    すでに参加してるよ
    <%= form_for :post, url: workshop_post_path(@workshop) do |f| %>
      <%= f.text_field :content %>
      <%= f.submit "投稿" %>
    <% end %>
  <% else %>
    <%= link_to "Join!!", create_user_workshop_path(@workshop), method: :post %><br>
  <% end %>
  <% @workshop.posts.each do |post| %>
    <%= post.content %>
  <% end %>
  誰でもゾーン
<% else %>
  No workshop
<% end %>